### ISSUE TITLE
Should format format the code in place?

### ISSUE THREAD

**Issue by gero3** [zz85/mrdoobapproves#10]
Since we start using code mirror, it seems more logically to format the code directly in code mirror instead of a new text area.

**Comment by zz85** [comment]
that's an option. but when you first mentioned diffing, i was planning to use http://codemirror.net/demo/merge.html

**Comment by zz85** [comment]
indeed this line 

``` js
codeEditor.setValue( checker.formatString(code + '\n') );
```

works well out of the box. however, it does "spoil the fun" of trying to format the code by hand...
