### ISSUE TITLE
Remove Check / Auto-Check functionality?

### ISSUE THREAD

**Issue by zz85** [zz85/mrdoobapproves#13]
Essentially linting in CodeMirror is automatic. Although with 047e7fa9270f1ecb050f91c8aa1ede64ee617ca2, both approach is supported, the question is -

Should we be remove the check + auto-check buttons to have auto-checking only?

**Comment by gero3** [comment]
I would at least leave the option because it really gets annoying when working with large files. or we have to make a worker do all the heavy lifting.

**Comment by zz85** [comment]
Great point! I'll leave the buttons there for now. It'd interesting to find out how well jscs will work in a worker but it's probably something I'll leave to later.
