### ISSUE TITLE
Transforms, Bundles & Workflows - Thinking about npm, browserify, bower, webpack, etc...

### ISSUE THREAD

**Issue by zz85** [zz85/mrdoobapproves#25]
Relates to #1, and partly a quick brain dump to wrap my head around all of these choices (so excuse me if it doesn't make sense right now)...
#### bower
- our current state of workflow.
- feels like a in-between of npm and wget. start with `bower.json`, `bower install` to download packages to `/bower_components/*` which we currently use to download codemirror & diff-merge-patch
- doesn't do anything else, we just load the components as static js assets
- development-wise we use the browser f5/refresh workflow
- bower components can be checked in to git
#### npm
- `npm install` downloads dependencies in `package.json` to `/node_modules`
- npm goes with hand-in-hand with node, they are node modules after all
- npm installed libs are typically not loaded directly from the browser, but would use something like browserify or webpack
- browserify and npm scripts is the current workflow for [timeliner](https://github.com/zz85/timeliner)
- node_modules not checked into git
#### require.js
- not to be confused require in node.js, it is a browser based module loader, although its offline optimizer can help create bundles too
- write modules in AMD style
- wasn't considering this approach for this project
#### browserify
- pretty powerful and useful for making node modules work in the browser
- our jscs is currently built with browserify
- typically use watchify if you like the "edit js files and refresh" workflow
- requires uglifyify for ulgified browserify transforms
#### webpack
- alternative workflow for the browserify workflow
- comes with development, watch and production mode builtin
- could support amd, commonjs, and normal js files
- can process css files too
- pretty customizable
- i'm pretty much inclined to try this
#### system.js, jspm
- universal dynamic module loader - es6 modules, cmd, commonjs, global scripts
- runs in the browser, so jspm needed for creating bundles
- jspm accepts npm/git repos
### gulp and grunt
- build tools with their own merrits but not planning to use them for this project

Broadly trying to categorize these tools, they can be thought to live more in the browser or on the filesystem (although distinction isn't always clear).

More browser-inclined
- bower
- requirejs
- systemjs

More cli based
- npm
- browserify
- webpack
- jspm
- gulp, grunt

Right now this app is simple and I don't really want to be too heavy on tools. I guess my choice right now is to try webpack (systemjs+jspm 2nd choice), and decide whether to move shift bower back to npm or leave them alone.

**Comment by zz85** [comment]
starting to try webpack, but haven't got to the point where i can nicely import all the js and css files. https://github.com/zz85/mrdoobapproves/compare/webpack_attempt will probably try again tomorrow or give up and try another solution...

**Comment by zz85** [comment]
i've made some progress with webpack, here's what it means if we were to use this workflow.
1. `npm install -g webpack` then npm install loader dependencies. make sense that we use package.json
2. webpack.config.js will define how we can bundle the app
3. run `webpack` to generate bundle. use `webpack --watch` in development mode to check for changes.
4. run `webpack -p` will produce production minified file

with `-p` the ugified output reduces code from 1.1MB -> 400kb (pre-gzipped).

What does this mean for our codebase?
- we could still use bower, but doesn't make as much sense to since it all can be done with npm
- if we npm install modules, then we can remove code from bower_components
- i will also point node_modules to @gero3 formatting branch
- converting our code closer to the a more commonjs style would help the webpack flow
- this is closer to the browserify approach which,
- also means: anyone who wants to try working on this project needs to run npm, webpack to actually see changes.

On another hand, we are already using browserify for jscs, so we could just use webpack bundling for just codemirror and jscs (which is 80% of our codebase), and keep main.js uncompressed.

how does this sound?

**Comment by gero3** [comment]
Looks great and works great now. The performance seems to have improved a lot by using a minified version.

**Comment by zz85** [comment]
cool, we'll use this workflow now. the only thing left using bower now is `diff_match_patch`, which the current codemirror merge add-on seems to be using the globalized script version of it rather than the npm version. it could possibly be fixed for the npm approach, but right now since bower_components is also checked in, there's no need for developers to install bower for this project.
