### ISSUE TITLE
Suggestion: Allow Tabs at Start of First Line

### ISSUE THREAD

**Issue by WestLangley** [zz85/mrdoobapproves#27]
See https://github.com/mrdoob/three.js/blob/master/examples/webgl_materials.html.

The first line in the main code block is indented:

```
            if ( ! Detector.webgl ) Detector.addGetWebGLMessage();
```

Allow the first line to define the default indentation for the remainder of the file, as is done in http://jsbeautifier.org.

**Comment by zz85** [comment]
hmm... i'm not sure how easy it to do this in jscs, but the not-so-elegant way can be done by transforming the editor's output to jscs, and mapping the transposed columns back...

but one way to solve this for now is to highlight all the code, hit Shift-Tab to un-indent all for checking first..

**Comment by WestLangley** [comment]
OK. That was why it was just a suggestion. :-)

**Comment by zz85** [comment]
I've came across this scenarios a couple of time, so its good you brought it up here too
