### ISSUE TITLE
help with copying your awesome formatting approach.

### ISSUE THREAD

**Issue by soliton4** [zz85/mrdoobapproves#34]
hi,
i got this in my inbox:
https://github.com/soliton4/nodeMirror/issues/18

i tried to figure out your code but jscs is still new to me and you are only providing a minified version in the demo, which makes it difficult.

you write you use a modified version of jscs, does that mean formatting is not possible with default jscs?
is https://github.com/zz85/node-jscs your modified version?

and is it enough if i use /lib/string-checker.js from it?

thank you in advance ;D

**Comment by zz85** [comment]
Hi, the source for our CodeMirror plugins is included in the root of this
repository.

The jscs formatter which you might already figured out, is using gero3 jscs
branch. This is documented in readme and also linked via package.json

**Comment by zz85** [comment]
Closing this since the official [jscs](https://github.com/jscs-dev/node-jscs) from 1.12.0 now supports auto-fixing. see https://medium.com/@addyosmani/auto-formatting-javascript-code-style-fe0f98a923b8 and issue 512 of node-jscs - https://github.com/jscs-dev/node-jscs/issues/516.
