### ISSUE TITLE
Unary Operators

### ISSUE THREAD

**Issue by WestLangley** [zz85/mrdoobapproves#35]
These should be the desired patterns, too, I believe:

```
x = ! false; // space following logical not
x = ~ y; // space following bitwise not
x = - 5; // space following unary negation (ditto, unary plus)
```

**Comment by mrdoob** [comment]
👍

**Comment by zz85** [comment]
@gero3 perhaps we could change https://github.com/gero3/node-jscs/blob/formatter/presets/mdcs.json#L21 to make it

``` json
"requireSpaceAfterPrefixUnaryOperators": ["++", "--", "!", "~", "-", "+", "^"],
```

or 

``` json
"requireSpaceAfterPrefixUnaryOperators": true
```

?

([Rule](http://jscs.info/rule/requireSpaceAfterPrefixUnaryOperators.html))

**Comment by zz85** [comment]
hmm, while I'm on this, I realize that node-jscs autofixing feature seems to be coming along pretty well. Maybe I'll make a PR to start using the offical jscs branch

**Comment by zz85** [comment]
![screenshot 2015-06-20 10 55 39](https://cloud.githubusercontent.com/assets/314997/8265748/eedf4ea0-173a-11e5-86b7-b574f79999f9.png)

**Comment by zz85** [comment]
@WestLangley @mrdoob if this is true, would 

``` js
if ( ! something ) {

}
```

be correct?

**Comment by WestLangley** [comment]
Looks correct to me. Also

```
!! something
```

**Comment by zz85** [comment]
@WestLangley we've a fix with the current jscs and offical autofixer running on http://zz85.github.io/mrdoobapproves/

Let us know if there are any abnormalities :)

**Comment by WestLangley** [comment]
Thanks!
