### ISSUE TITLE
Whitespaces

### ISSUE THREAD

**Issue by zz85** [zz85/mrdoobapproves#4]
the current node-jscs mdcs seems to be accepting

``` js
if (x) {

}
```

as valid when it should be

``` js

if ( x ) {

}
```

i think we need to set `requireSpacesInsideParentheses`?

**Comment by gero3** [comment]
I still have to write the format for this one but I added the check already to formatting branch [commit](https://github.com/zz85/mrdoobapproves/commit/5fe9400bd0ce3183042f860a425f7f33b392649f).
