### ISSUE TITLE
function name in closured functions

### ISSUE THREAD

**Issue by WestLangley** [zz85/mrdoobapproves#45]
Which pattern should mrdoobapproves support?

``` javascript
foo: function () {

    return function foo( args ) { // no space

    };

}(),
```

or

``` javascript
foo: function () {

    return function foo ( args ) { // with space

    };

}(),
```

Or, for that matter,

``` javascript
function mrdoob() { // no space

}
```

or

``` javascript
function mrdoob () { // space

}
```

/ping @gero3
/ping @mrdoob 
/ping @zz85

**Comment by mrdoob** [comment]
There shouldn't be space between the name of the function and the parenthesis.

``` javascript
function () { // space
```

``` javascript
function mrdoob() { // no space
```

**Comment by zz85** [comment]
good point, we don't have a rule for that currently. we could use http://jscs.info/rule/disallowSpacesInFunctionDeclaration.html for that

**Comment by zz85** [comment]
This should now work in http://zz85.github.io/mrdoobapproves/
