### ISSUE TITLE
'else' and 'else if' formatting

### ISSUE THREAD

**Issue by WestLangley** [zz85/mrdoobapproves#46]
``` javascript
if(a===1){
    x = 0;
}else if(a===2){
    x=2;
}
```

formats as

``` javascript
if ( a === 1 ) {

    x = 0;

}else if ( a === 2 ) { // should be a space before 'else'

    x = 2;

}
```

**Comment by WestLangley** [comment]
``` javascript
if(x===0) {
} else if(x===1) {
y = 0;
}
z = 0;
```

formats as

``` javascript
if ( x === 0 ) {
} else if ( x === 1 ) {

    y = 0;

}
z = 0;

```

**Comment by zz85** [comment]
@gero3 are you working on this issue?

**Comment by zz85** [comment]
@gero3, this can be fixed with [requireSpaceBeforeKeywords](http://jscs.info/rule/requireSpaceBeforeKeywords). If you're busy let me know so I could help add that in and make a PR to jscs.

**Comment by zz85** [comment]
Also, I've included our own preset so we do not have to wait for jscs release cycles. https://github.com/zz85/mrdoobapproves/blob/gh-pages/index.html#L235
