### ISSUE TITLE
Support ES6 Template Strings

### ISSUE THREAD

**Issue by theo-armour** [zz85/mrdoobapproves#47]
How about adding support for the new ES6 Template Strings - the strings `beginning and ending with`?

**Comment by zz85** [comment]
Do you mean like 

``` js
`string text ${expression} string text` 
```

?

**Comment by theo-armour** [comment]
Yes please!

**Comment by zz85** [comment]
This should now work in http://zz85.github.io/mrdoobapproves/

**Comment by theo-armour** [comment]
Looks good to me. Thank you , Joshua.
