### ISSUE TITLE
Switch statement formatting

### ISSUE THREAD

**Issue by WestLangley** [zz85/mrdoobapproves#55]
This appears to be the way @mrdoob prefers it.

``` javascript
switch ( event ) {

    case THREE.ConstantA:

        foo();
        break;

    case THREE.ConstantB:

        bar();
        break;

}
```

Maybe this is OK, too.

``` javascript
switch ( event ) {

    case 1: foo(); break;

    case 2: bar(); break;

}
```

**Comment by zz85** [comment]
These 2 blocks seems to [pass current tests](https://github.com/zz85/mrdoobapproves/commit/fd68c27c818de27168c09f1874cd8ec5ea5b8270), do you have examples that would fail the current style guide?

**Comment by WestLangley** [comment]
``` javascript
switch(event){
case THREE.ConstantA:
foo();
break;
case THREE.ConstantB:
bar();
break;
}
```

**Comment by zz85** [comment]
I've added a test for it. https://github.com/zz85/mrdoobapproves/pull/60/commits/7da3737f9d6b2613aba8edca7941510589c49ad6 

Thankfully the current rules catches this, both jscs or eslint formatting does indent them during auto fixing but doesn't format them exactly with the line break style. 

To support this seems to require an addition of a new rule or plugin to Eslint https://github.com/eslint/eslint/issues/6619

**Comment by WestLangley** [comment]
What about the required space before the `{`  ?

**Comment by zz85** [comment]
The new ESLint version seems to add a space fixes for it https://zz85.github.io/mrdoobapproves/#eslint

I think I should start to make ESLint the default engine and archive the old formatter...

**Comment by zz85** [comment]
Closing long fixed issue
