### ISSUE TITLE
Tern JS Refactoring

### ISSUE THREAD

**Issue by zz85** [zz85/mrdoobapproves#6]
I just came across this which is available also a plugin for codemirror.

http://ternjs.net/doc/demo.html

Thought it's pretty cool that it's able to do refactoring-style renaming (the only IDE i know right now which does that for JS is jetbrains webstorm), and I imagine it would have been pretty useful a couple of time when @mrdoob renamed things around in three.js..

**Comment by mrdoob** [comment]
There is also a package for Atom ^^
https://atom.io/packages/Tern

**Comment by zz85** [comment]
It feels like mrdoob have been changing editors: gedit > sublime > atom :laughing:

**Comment by mrdoob** [comment]
Hehe! I still use gedit on Linux but I replaced Sublime with Atom on OSX ^^

**Comment by zz85** [comment]
Since Ternjs is available in [three.js's editor](https://github.com/mrdoob/three.js/pull/6654) and atom, I think I would keep this editor more focused on code checking and styling and not implement this now (since ternjs might be more useful for code writing and editing).

**Comment by mrdoob** [comment]
Sounds good! 👍

**Comment by zz85** [comment]
Haha revisiting this thread almost a year later, and I find myself using [Microsoft Visual Studio Code](https://code.visualstudio.com/) more these days.

**Comment by zz85** [comment]
Closing as I'm personally not finding this useful anymore.
