### ISSUE TITLE
Simple question...

### ISSUE THREAD

**Issue by Itee** [zz85/mrdoobapproves#61]
Is this include in the build chain of mrdoob three.js repo as tools or dependencies ? Because i saw in Threejs/utils/codestyle a config.json but i'm not sure this is the same thing !
Maybe a noob question, but....

Thank in advance,
Tristan

**Comment by zz85** [comment]
Hmm... no.

I just taken a quick look at codestyle utils there, my guess is that it's using an older configuration of JSCS. The config used in this repo is probably slightly more comprehensive.

**Comment by Itee** [comment]
Ok, have you plan to include this as utile dependency in three.js, do you know what think mrdoob about that ? Have you talk about the possibility of this happening ?

**Comment by zz85** [comment]
Actually I would suspect the utils in threejs might not be used often. Maybe @mrdoob knows better.

I would think the approach going forward would be to expose the eslint config as a module (see https://github.com/zz85/mrdoobapproves/issues/63)

**Comment by mrdoob** [comment]
Yeah, I think I'll remove that folder...

**Comment by mrdoob** [comment]
Done! https://github.com/mrdoob/three.js/commit/0b86af3923f57caad399e3a5503e3bc3e2ee5666

**Comment by zz85** [comment]
Closing this with https://github.com/mrdoob/three.js/pull/10129 :)
