### ISSUE TITLE
Formatting problem

### ISSUE THREAD

**Issue by WestLangley** [zz85/mrdoobapproves#65]
Auto-format can't handle this unary operation.
```
function foo() {

	this.bar = 1;

	this.bar ++;

}
```

**Comment by WestLangley** [comment]
/ping @zz85 

Is it fixable?

**Comment by zz85** [comment]
hmm, this looks like a bug with `eslint` `space-unary-ops` auto fix rule.

eg. `moo.cow++` become `moo .cow++`  which is also wrong...

**Comment by zz85** [comment]
just filed a bug @ https://github.com/eslint/eslint/issues/9792 I'll try to see if I can make a patch to eslint.

**Comment by zz85** [comment]
@WestLangley Problem seems fixed now! on https://zz85.github.io/mrdoobapproves/
